server:
  port: 8080

spring:

  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 150MB

  application:
    name: Capstone-Newri
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddlAuto: create
#      ddlAuto: create-drop
      ddlAuto: update
      #ddlAuto: validate
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
    database: postgresql

  profiles:
    include: KEY
