server:
  port: 8080

spring:

  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 150MB

  application:
    name: Capstone-Newri
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/
    username: postgres
    password: postgres

  jpa:
    hibernate:
#      ddlAuto: create
#      ddlAuto: create-drop
      ddlAuto: update
      #ddlAuto: validate
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
    database: postgresql

jwt:
  header: Authorization
  secret: sejongUniversityCapstoneProjectTeamNameNewri
  token-validity-in-seconds: 86400

flask:
  url: http://34.64.103.62:5000
